# Generated by Django 5.2.1 on 2025-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('formatt', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sertificate', models.BooleanField()),
                ('photo', models.ImageField(upload_to='course_photos/')),
            ],
        ),
    ]
