# Generated by Django 5.2.1 on 2025-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avg_grade',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='course',
            name='stud_amount',
            field=models.IntegerField(default=0),
        ),
    ]
