# Generated by Django 5.2.1 on 2025-06-04 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_courses', '0002_course_avg_grade_course_stud_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='formatt',
            new_name='format',
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_grade',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='stud_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
