# Generated by Django 5.2.1 on 2025-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_info', '0002_remove_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
    ]
